<?
        $title = "Email Address Parsing Tests";
        include('../../../head.txt');

	include('reader.php');
	include('../utils/markdown.php');

	$GLOBALS['pageuids']=1;

	function test_table($show){

		$uid = $GLOBALS['pageuids']++;
		$num = count($show);

		echo "<div id=\"tests-{$uid}-1\"><a href=\"#\" onclick=\"show('$uid'); return false;\" style=\"font-size: 12px;\">Show $num tests</a></div>\n";
		echo "<div id=\"tests-{$uid}-2\" style=\"display: none;\"><a href=\"#\" onclick=\"hide('$uid'); return false;\" style=\"font-size: 12px\">Hide tests</a><br />\n";

		echo "<table border=1>\n";
		echo "<tr><th>ID</th><th>Address</th><th>Expected</th></tr>\n";
		foreach ($show as $id){
			$test = $GLOBALS['tests'][$id];

			$address = $test['address'];
			$address = wordwrap($address, 50, "{FORCEBREAK}", true);
			$address = HtmlSpecialChars($address);
			$address = str_replace(array("\r","\n"," ","\0"), array("&amp;#13;","&amp;#10;","&nbsp;","&amp;#0;"), $address);
			$address = str_replace('{FORCEBREAK}', "\n ", $address);

			echo "<tr>";
			echo "<td>$test[id]</td>";
			echo "<td><small>".HtmlSpecialChars($address)."</small></td>";

			if ($test['valid']){
				if ($test['warning']){
					echo "<td>Pass w/ Warning</td>";
				}else{
					echo "<td>Pass</td>";
				}
			}else{
				echo "<td>Fail</td>";
			}
			echo "</td></tr>\n";
		}
		echo "</table>\n";

		echo "</div>\n";
	}

?>

<script>
function show(uid){
	document.getElementById('tests-'+uid+'-1').style.display = 'none';
	document.getElementById('tests-'+uid+'-2').style.display = 'block';
}
function hide(uid){
	document.getElementById('tests-'+uid+'-1').style.display = 'block';
	document.getElementById('tests-'+uid+'-2').style.display = 'none';
}
</script>

	<h1>Email Address Parsing Tests</h1>

	<p>This documentation is automatically generated by the tags and glossary from the <code>tests.xml</code> file.</p>
	<p>It attempts to explain what certain groups of tests are checking for and why, with links to relevant RFC sections.</p>

<?
	foreach ($glossary as $k => $row){

		echo "<h2 style=\"background-color: #eee\">$row[title]</h2>\n";

		$ids = array();
		foreach ($tests as $test){
			if (isset($test['tags']) && in_array($k, $test['tags'])){
				$ids[] = $test['id'];
			}
		}
		test_table($ids);

		echo Markdown($row['desc']);
	}
?>

<?
        include('../../../foot.txt');
?>

